name = "cartasahora-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "d149d7ddb5563d01911c96de5a1f0ae5"

[[kv_namespaces]]
binding = "PAGOS_KV"
id = "0be7b496e54842cf80d2b141f7de8b58"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "5855ba84011c42c4a526e2cae18e9fde"

[[kv_namespaces]]
binding = "LEADS_KV"
id = "c3f4a718ac1649f5abac888b3485fed9"
